version: "3.7"

services:
  website:
    container_name: website
    build:
      context: ./website
      dockerfile: Dockerfile
    volumes:
      - "./website:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
